### PR TITLE
draft: Gamemode: Payload

### PR DESCRIPTION
**Pull request by PhantomEpicness**
## Abstract
_this was an idea on discord that sparked great interest for me, I forgot who came up with it but its getting its own design doc so it can be looked at and probably added within the next year or two_

This is an entirely new gamemode for CM-SS13, directly inspired from Valve's Team Fortress 2 Gamemode of similar naming, where it follows almost the exact same gameplay from there.
We have seen WO, an absolute defense gamemode where one side is forced to bash their head against cades until they win, but what about a marine version of WO? What about a game mode that forces attack above all else?
In this game mode, marines will have to push an experimental xenocidal bomb in an infested mine to the mining pit, where the heart of the hive resides below.

## Goals

1. Make a new game mode that is focused soley on the push to victory
    Cadehugging should absolutely be shafted to hell and back in this gamemode as pushing is the way to advance. Mechanics should reflect this.

2. Maps should be linear, but allow flanking on linear push points.
    The main push shall be the largest and intentional chokepoints should always have flanks.

3. Marines should not be able to kill all of the Xenos.
    The way the game mode should be designed is that numbers still matter to the xenos, so they don't suicide charge, but they are given just enough handouts to barely defend against the marines. Hive should be a safe space for xenos, either through one way doors or being in admin Z level with a tunnel connecting it

4. Reduce attrtion and stalemates seen in normal gameplay.
    Stalemates are awful and this gamemode is meant to keep everything moving. The checkpoint system with achievable goals that reward both sides to keep the round in motion shall achieve this

## Non-goals

1.  Have PMCs/survivors be too dominant in the gamemode
    Survivors in the gamemode are meant to be to keep xenos busy early game while forcing PMCs to split up to rescue them and enable power.

## Content

The payload can only move forward on the tracks and is indestructable

The tracks cannot have anything placed on them and are invincible.

### Story

`When the colony on ___ was taken over by [REDACTED], its PMC outpost managed to hold out long enough for marine and additional PMC reinforcements arrived along with a highly experimental xenocidal bomb. However, the hive is in a deep mining cave pit and the bomb ain't gonna push itself down there..

Our objective is simple: Spearhead through the xeno defenses while pushing the cart.` 

Xeno major
`With the marines destroyed and the only sample of the xenocidal bomb lost, the human war against the xenomorph took a serious blow....`

Xeno major (hive surge time victory)
`The cave starts rumbling... and the motion detectors light up like a Christmas tree.... the hordes are here and there is nothing stopping them now...`

Marine major

` With the xenocidal bomb proven to work, fighting Xenos becomes significantly easier and with minimal damage to the expensive colony. The USCM is immediately equipped with these, including the Dust Raiders, who notably used it during a Xenomorph siege on their base and retook LV-624. By the 2200s, the xenomorph became no more than a footnote that wiped out a few middle-of-nowhere rimworld colonies. `

### Maps
The gamemode will feature its own maps, being linear with, ideally, different routes marines can take for the payload. Other than the main routes, there wont be much besides intentional chokepoints having their own dedicated flanking routes. Random possible invisible checkpoints will be placed along the rail track to trigger events if the payload passes them.

Survivors may spawn with an ID card that unlocks an additional route for the payload to move through.

Having them randomly selected out of a possible pool discourages metagaming them.

Each map however has to have a prebuilt FOB with sufficient prebuilt defenses, with an added ERT shuttle LZ and the bomb location (mining pit) with several pre spawned acid pillars.

### Round start/Early game

PO roll will be removed. No CAS will exist as everything is deep underground. No mortar spawns either. Either OBs or a limited use rail gun is avalible.

PO role will be replaced with W-Y contracted vegetation specialists who come with chainsaws. These chainsaws saw through xeno walls after a short interaction, however they must be completely covered in doing so as its interruptable.

CL will be replaced with war reporter because why not.

APC is meant to act as a mobile FOB to keep the marines going, and the map should be designed to where it can only move along the main tunnel and cannot push the payload.

Survivor roles renamed will be active and given better equipment. 

PMC roles will be avalible and spawn in a prebuilt FOB. Their primary objective before the marines arrive is to search for and rescue survivors and to activate power. Activating power is highly beneficial as the floodlights in the mine will be turned on, distracting xenos from building.

PMCs and survivors primary intention, however, is to give Xenos something to do before the marines arrive as they have to prioritize erecting defenses while preventing power from being repaired and survivors from escaping.

Marines will spawn in the almayer as normal to drop at 12:25.

Xenos on the otherhand will have an immovable, pre placed hive away from the objective with a larva amount that is not infinate, but gradually. This makes so xenos will not have to focus on captures, while still having some risk remaining so suicide charging is discouraged. In addition, all larva start with full evo so they may evolve instantly.

Deep in the caves beyond survivor spawns will indestructable doors that will prevent hive diving PMCs and survivors. These doors will turn destructable when the mid game starts.

The role of queen in the gamemode still being contemplated as she will be forcefully glued to the ovi. 

If PMCs recover 75% of the survivors, they get a greentext. These survivors may join the fight in the mid game as PFC+ along with remaining PMCs

### Mid-late game

The mid game starts when the marines arrive and the Xenocidal Bomb is placed on a mining cart to be pushed to its objective. Once the payload moves out of FOB, the xeno evolution rate is doubled.

 As the marines move the payload, they will activate the invisible checkpoints, triggering certain events.
 These events are:
    - All checkpoints for marines: Will get a choice between a pre-equipped ERT spawning at the ERT dock or 5+ railgun shells
    - First checkpoint: Xenos get a T1 ERT that spawns behind marine lines + a couple larva bonus.
    - Second checkpoint: Xenos get an XRT with 1 garunteed boiler spawn + larva bonus
    - Third checkpoint: Xenos get an XRT with a scalable about of T3s spawning depending on pop + large larva bonus
### Endgame

Upon fighting fiercly to the pit, marines will have to push the actual bomb into the pit. This is a X minute interation that is interruptable as xenos fight for their lives in an epic battle for the fate of the hive.

### Win conditions

Xenos can win by
    - Time, as marines have to get the payload within X hour and X minutes
    - Killing all marines groundside. Hijack is disabled and they will win immediately upon taking groundside.

Marines can win by:
    - Pushing the payload to the pit and destroying the hive with the xenocidal bomb. Ooorah!

## Potential Changes

Too biased toward one side
    Adjust the checkpoint rewards to compensate. Alternatively can take more drastic measures such as adding consistant respawns for a side, restricting xeno wall building till X time. adjusting amounts of AP ammo or spawning marines pre equipped on FOB akin to WO to limit their loadout choices.

### CODE REVIEW

**Comment by PhantomEpicness** [comment]
extremely undercooked design doc, just wanted to put the idea down + need feedback

**Comment by hotimep** [comment]
tf2 voicelines play at random (requirement)

**Comment by PhantomEpicness** [comment]
> tf2 voicelines play at random (requirement)

would be funny to replace warcries with tf2  voicelines for the gamemode

and possible too since valve is historically extremely lenient with this type of stuff

**Comment by PhantomEpicness** [comment]
Idea: have ERT docks or elevators near a Frontline unlocked when a checkpoint is reached so that pre equipped ERTs can spawn closer.

**Comment by stanalbatross** [comment]
cm is not tf2

**Comment by PhantomEpicness** [comment]
> cm is not tf2

wym we have the same classes
Medic
Heavy (sg)
Demoman (demoman)
Soldier (sadar)
Engineer
scout (deltard with shotgun and service jacket)
spy (scout spec with xenosuit)
Sniper (sniper spec)
Pyro (Pyro spec)

**Pull request closed without merging**
